<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>97a4f173-0978-4401-a1f9-c794165f92bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div[4]/div/div/div/div[2]/form/div[3]/div/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tutor-login-modal.open > div.row.student-login-modal-inner.align-items-center.justify-content-around > div.col-12.col-sm-12.col-md-12.col-lg-10.col-xl-8 > div.row > div.col-12 > form.ant-form.ant-form-horizontal.login-form > div.full-width.mb-3.mt-2 > div.row.login-input > div.col-12.col-sm-12.col-md-4.col-lg-4.col-xl-4 > button.ant-btn.ant-btn-primary.btn.btn-sm.btn-login > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;page-container&quot;]/div[@class=&quot;page-body-container&quot;]/div[@class=&quot;container&quot;]/div[1]/div[@class=&quot;login-page-container tutor-login-open modalFunction&quot;]/div[@class=&quot;row login-height align-items-center justify-content-around&quot;]/div[@class=&quot;tutor-login-modal open&quot;]/div[@class=&quot;row student-login-modal-inner align-items-center justify-content-around&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-12 col-lg-10 col-xl-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/form[@class=&quot;ant-form ant-form-horizontal login-form&quot;]/div[@class=&quot;full-width mb-3 mt-2&quot;]/div[@class=&quot;row login-input&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4&quot;]/button[@class=&quot;ant-btn ant-btn-primary btn btn-sm btn-login&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div[4]/div/div/div/div[2]/form/div[3]/div/div/button/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login using your email ID'])[2]/following::span[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/following::span[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signup here'])[2]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/form/div[3]/div/div/button/span</value>
   </webElementXpaths>
</WebElementEntity>
