<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>classes_taught</description>
   <name>classes_taught</name>
   <tag></tag>
   <elementGuidId>8e6d9560-cd7c-4fde-8058-2bcd3c116048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='classes_taught']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
