<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add Class</name>
   <tag></tag>
   <elementGuidId>2cc56844-0875-4b68-bb21-fe6eba52cb34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='Add a Class']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tutor-add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4c1cc4df-a5d5-4e25-abb5-ac1ac1e9bf9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tutor-add</value>
      <webElementGuid>039373d5-ad7c-4d62-948a-e159d3d9c11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add Class</value>
      <webElementGuid>2e11e170-6746-49e9-8517-22bab224b33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;page-container&quot;]/div[@class=&quot;page-body-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-12 col-lg-9 col-xl-9&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4&quot;]/div[@class=&quot;nurtem-card-design py-4 mt-4 mb-3&quot;]/div[@class=&quot;row justify-content-center align-items-center&quot;]/a[1]/div[@class=&quot;col&quot;]/div[@class=&quot;tutor-add&quot;]</value>
      <webElementGuid>49992003-d92b-4c62-9d21-43519929aa93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div/div/div/div/a/div/div</value>
      <webElementGuid>20b02b8f-f03e-4467-8fa4-578f3af6b77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classes'])[1]/following::div[2]</value>
      <webElementGuid>bcbd094e-4da9-49cc-8645-95973fca621a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::div[12]</value>
      <webElementGuid>d16aacf8-2682-4825-9db4-44af329ea91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Camps'])[1]/preceding::div[3]</value>
      <webElementGuid>ede8a912-725b-49e7-9850-a71757c1ac77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div</value>
      <webElementGuid>7b81feba-d483-459e-b483-5a3b98a4f978</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
