<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>mobile</description>
   <name>mobile</name>
   <tag></tag>
   <elementGuidId>3d92b522-fdae-4ec4-add0-2792a283d9e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mobile_number']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
