<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>scroll</name>
   <tag></tag>
   <elementGuidId>c278110b-953e-4b27-bfcd-842978c0a03d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[normalize-space()='Action']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
